export const SET_USER_ACTION = "SET_USER_ACTION";
export const GET_USER_ACTION = "GET_USER_ACTION";
export const REMOVE_USER_ACTION = "REMOVE_USER_ACTION";
export const SET_USER_DETAIL_ACTION = "SET_USER_DETAIL_ACTION";
export const GET_USER_DETAIL_ACTION = "GET_USER_DETAIL_ACTION";
export const REMOVE_USER_DETAIL_ACTION = "REMOVE_USER_DETAIL_ACTION";
export const RESET_USER_REDUCER_ACTION = "RESET_USER_REDUCER_ACTION";
