export const PRIVATE_ROUTE = [{ path: "/dashboard" }, { path: "/settings" }]
export const PRIVATE_ROUTE_IGNORE_SIDEBAR = [{ path: "/settings" }]
export const AUTH_ROUTE = [{ path: "/auth/login" }, { path: "/auth/register" }, { path: "/auth/verify" }]
export const PUBLIC_ROUTE = [{ path: "/" }]
export const PROTECTED_API_ROUTE = [{ path: "/api/auth/change-password" }]
