import React from "react";
import CustomProviders from "./providers";
import { Metadata } from "next";
import "./assets/scss/style.scss"
import "./assets/css/output.css"
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "./favicon.ico",
  },
};

function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="bumblebee">
      <body className="font-san-francisco" suppressHydrationWarning={true}>
        <CustomProviders>
          {children}
        </CustomProviders>
      </body>
    </html>
  );
}
export default RootLayout;
