export const SET_MENU = '@CUSTOMIZATION/SET_MENU';
export const MENU_TOGGLE = '@CUSTOMIZATION/MENU_TOGGLE';
export const MENU_OPEN = '@CUSTOMIZATION/MENU_OPEN';
export const SET_FONT_FAMILY = '@CUSTOMIZATION/SET_FONT_FAMILY';
export const SET_BORDER_RADIUS = '@CUSTOMIZATION/SET_BORDER_RADIUS';
export const RESET_CUSTOMIZATION_REDUCER_ACTION = "@CUSTOMIZATION/RESET_CUSTOMIZATION_REDUCER_ACTION"